### ISSUE TITLE
How to run your work？

### ISSUE THREAD

**Issue by yhjiujiu** [CDboyOne/IHGNN#1]
hi，can you give me a running command? Thanks

**Comment by CDboyOne** [comment]
Sorry but I am quite busy recently, I will complete the documentation as fast as I can.

**Comment by liu-jc** [comment]
Hi @CDboyOne,

Any updates for the documentation?

**Comment by CDboyOne** [comment]
I will update recently.

发件人: Juncheng ***@***.***>
发送时间: 2022年7月5日 20:10
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [CDboyOne/IHGNN] How to run your work？ (Issue #1)


Hi @CDboyOne<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCDboyOne&data=05%7C01%7C%7C2200da8cd78e483282a608da5e7f6159%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637926198446580360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9pHZLNgod7tHX1z38wXj3h4%2Fq21n0Fx%2Bs%2FEfuG%2F984U%3D&reserved=0>,

Any updates for the documentation?

―

**Comment by Evanism824** [comment]
Hi，can you provide the dataset?

**Comment by Evanism824** [comment]
Hi,could you provide the dataset? Thank you.

**Comment by CDboyOne** [comment]
Hi, Amazon datasets and CIKM dataset can be downloaded from public websites. Alibaba dataset cannot be published due to privacy policies of Alibaba.

发件人: ***@***.***>
发送时间: 2022年8月16日 22:54
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [CDboyOne/IHGNN] How to run your work？ (Issue #1)


Hi,could you provide the dataset? Thank you.

―

**Comment by CDboyOne** [comment]
Hi, Amazon datasets and CIKM dataset can be downloaded from public websites. Alibaba dataset cannot be published due to privacy policies of Alibaba.
